### ISSUE TITLE
Table row's class of "row" conflicts with bootstraps' row class

### ISSUE THREAD

**Issue by paperdigits** [infotexture/dita-bootstrap#1]
By default, a table row is `<tr class="row">`, which picks up bootstraps grid layout class which is also named row. This results in tables rendering really poorly. 

If I change the table rows' class to `table-row`, then it renders correctly.

I can't seem to find where in the HTML transform the `<tr>` picks up it's class. Any pointers to which template I can override  be great.

**Comment by infotexture** [comment]
For details, see https://github.com/dita-ot/website/issues/160#issuecomment-464402549.
