### ISSUE TITLE
toc

### ISSUE THREAD

**Issue by Gurushesh-Metapercept** [infotexture/dita-bootstrap#112]
hey, I'm using the dita-bootstrap plugin .. when I'm generating output it creates one toc.index file in the root folder of the output. so my question is can use a style that toc.index file? I want to add CSS and JS for that toc.index file too. how can I do this?

**Comment by jason-fox** [comment]
That `toc.html` file is generated as part of the underlying DITA-OT HTML5 transform.

The DITA-OT [documentation](https://www.dita-ot.org/dev/parameters/parameters-html5.html) states:

>  - `args.html5.toc` - Specifies the base name of the TOC file.
> - `args.html5.toc.class` - Specifies the value of the @class attribute on the <body> element in the TOC file.
> - `args.html5.toc.xsl` - Specifies a custom XSL file to be used for TOC generation.

So yes you could write a custom XSLT transform to style that TOC file if you wanted, but it is not functionality held within the Bootstrap plug-in.
