### ISSUE TITLE
Nav ToC regressions

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap#128]
While updating the nav ToC screenshots in https://github.com/infotexture/dita-bootstrap/commit/6ee2717a1f828c04bc0cd5474008c57db756595a for #125, I noticed that the ToC text size, padding and margins have changed.

Some of these differences may be caused by upstream changes in recent Bootstrap versions, whereas others are likely related to layout and style changes in recent PRs here, such as those that adjust the layout for the in-page scroll spy navigation area for page ToCs on the right.

- ToC width has decreased and font size increased, so longer headings may wrap less favorably (see #89)
- ~~In the default DITA-OT `full` and `partial` modes, there is no longer any gutter between the ToC and the page content, so longer headings touch body text.~~
- In `nav-pill-*` modes:
  - additional padding appears between the ToC background and active pill
  - ~~there is no gutter between ToC and page content (ToC box touches body text)~~
  - increased padding between items means fewer ToC items fit on screen
- ~~In `list-group-*` modes, the gutter is narrower than before.~~

(See before/after screenshots in https://github.com/infotexture/dita-bootstrap/commit/6ee2717a1f828c04bc0cd5474008c57db756595a for examples.)

@jason-fox Like #127, there's probably no need to hold up the 5.3.3 release for this, but I wonder if we should switch the default ToC option to `collapsible`, since that's what seems to work best now — and it's what we use on the project website.

**Comment by jason-fox** [comment]
A lot of this is due to Bootstrap's CSS restricting  the container width to 1320px

```
media (min-width: 1400px)
.container, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
    max-width: 1320px;
}
```

**Comment by infotexture** [comment]
Turns out several of the problems mentioned above were caused by the outdated Chromium renderer I used to capture the screenshots in 6ee2717.

I was able to resolve several ~~obsolete~~ items above by recapturing with Safari in db1c011.

**Comment by infotexture** [comment]
Closing this as stale, since several of the originally reported regressions are obsolete, and the font size issues in `nav-pill-*` modes don't seem to be a deal-breaker for anyone.
