### ISSUE TITLE
DITA <imagemap> doesn't display correctly

### ISSUE THREAD

**Issue by super-structure** [infotexture/dita-bootstrap#143]
The `topic.fig` template in `Customization/XSL/topic.xsl` appear to override the default HTML5 processing for `<imagemap>` elements (which of course are specialized from `<fig>`. As with the templates exception for `<syntaxdiagram>` element, I think just adding an exception for the imagemap (by class) seems to resolve the issue.

**Comment by infotexture** [comment]
@super-structure Thanks for reporting this. 

Are you able to submit a pull request with the proposed changes?
