### ISSUE TITLE
dark.mode.include=no not working

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#152]
Setting the **dark.mode.include** parameter to **no** still creates the link to the .js file and thus enables dark mode. 

In the _insertParameters.xml_ file the parameter is called **BOOTSTRAP_DARK_MODE_INCLUDE**, but in the _html5-bootstrap.xsl_ it's called **BOOTSTRAP_DARK_MODE_TOGGLER_INCLUDE**. 

Naming them similarly fixes the issue.

**Comment by infotexture** [comment]
@lakokkonen Good catch, thanks for reporting. 🙏
