### ISSUE TITLE
TOC items created as collapsible incorrectly 

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#160]
**ISSUE:**

Using the _collapsible_ **nav-toc** parameter, the TOC items are created with the collapsible chevron button even if the topicref only has children that are set as _toc="no"_ in the DITA Map.

![collapse_toc](https://github.com/infotexture/dita-bootstrap/assets/108674366/39e545c1-b8f8-4d91-a832-75ac4e0473d9)

In the image, the Product 1 and Product 2 have child topics that are set as _toc="no"_. 

So having any child topic will cause the nav item to be a collapsible one, even if there's nothing to collapse.

**POSSIBLE SOLUTION:**

I tried modifying the **children** parameter in the corresponding template in **nav.xsl**, and it seems to work:

`<xsl:param name="children" select="*[contains(@class, ' map/topicref ')] [not(@toc = 'no')] [not(@processing-role = 'resource-only')]" as="element()*"/>`

**Comment by infotexture** [comment]
@lakokkonen Thanks for reporting this issue. 🙏 

Are you able to submit a pull request with the proposed changes?

**Comment by lakokkonen** [comment]
@infotexture Sure, should I fork the repo and create the pull request from there?

**Comment by jason-fox** [comment]
@lakokkonen - Yes, that is the process I and others have used to make contributions here.
