### ISSUE TITLE
DITA-OT 4.2 compatibility

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap#165]
When testing #163 & #164 with the current state of the DITA-OT `release/4.2` branch (dita-ot/dita-ot@2a2c3f2), the nav ToC sidebar `bs-sidebar` appears _above_ the page content at desktop breakpoints, rather than in the left column as intended.

The same code in these PRs works fine when built from the DITA-OT `master` branch (v4.1.2).

Not sure yet if this is a bug in the current state of the DITA-OT release branch, or whether recent changes have rendered the custom XSL code in the DITA Bootstrap plug-in incompatible with the upcoming DITA-OT 4.2 release.

Can't debug further right now, so filing this as a reminder that it's something we'll need to investigate before we package up the new plug-in versions.

**Comment by jason-fox** [comment]
This isn't an issue with the  `dita-bootstrap`, its a problem within the hook to the `fox.jason.extend.css` dependency. You can confirm this by adding a `<fail/>` to  `process_css_extend.xml`:

```xml
<target name="extend.css.copy">
    <fail/>
</target>
```


If you run this on 4.1.2 then the build fails since `extend.css.copy` is being called as an extension point of `depend.preprocess.copy-html.pre` as defined in the plugin.xml.

```xml
<feature extension="depend.preprocess.copy-html.pre" value="extend.css"/>
```

If you run this on the 4.2 branch then the build runs to completion because `extend.css.copy`  is never called.

Unfortunately `extend.css.copy` is responsible for generating the CSS file that places the ToC on the right (amongst other things). You will notice that the Prism highlighting has also disappeared for the same reason.

**Comment by jason-fox** [comment]
My investigation leads to the idea that the preprocess2 ANT is missing the extension hooks:

Compare `build_preprocess_template.xml`:

```xml
<target name="copy-html"
    dita:depends="{depend.preprocess.copy-html.pre}"
    dita:extension="depends org.dita.dost.platform.InsertDependsAction"
    unless="preprocess.copy-html.skip"
    description="Copy html files">
    <condition property="copy-html.todir" value="${_dita.map.output.dir}/${uplevels}" else="${dita.output.dir}">
      <equals arg1="${generate.copy.outer}" arg2="1"/>      
    </condition>
    <copy todir="${copy-html.todir}" failonerror="false" overwrite="true">
      <ditafileset>
        <excludes format="dita"/>
        <excludes format="ditamap"/>
        <excludes format="ditaval"/>
        <excludes format="image"/>
        <excludes format="coderef"/>
      </ditafileset>
      <jobmapper/>
    </copy>
  </target>
  ```


And `build_preprocess2_template.xml`

```xml
<target name="copy-html2" 
          unless="preprocess.copy-html.skip" 
          description="Copy html files">
    <copy todir="${dita.output.dir}" failonerror="false" overwrite="true">
      <ditafileset>
        <excludes format="dita"/>
        <excludes format="ditamap"/>
        <excludes format="ditaval"/>
        <excludes format="image"/>
        <excludes format="coderef"/>
      </ditafileset>
      <jobmapper/>
    </copy>
  </target>
  ```

**Comment by jason-fox** [comment]
Adding the lines:

```diff
<target name="copy-html2" 
          unless="preprocess.copy-html.skip" 
+        dita:depends="{depend.preprocess.copy-html.pre}"
+        dita:extension="depends org.dita.dost.platform.InsertDependsAction"
          description="Copy html files">
```

And reinstalling the plugins fixes the issueor 4.2.

**Comment by infotexture** [comment]
That's right: In DITA-OT 4.2, the HTML5 transformation uses map-first preprocessing, which no longer provides access to the legacy pre-processing extensions like `depend.preprocess.copy-html.pre`.

Could the `fox.jason.extend.css` plug-in be updated to use the `depend.preprocess.pre` or `depend.preprocess.post` extension points for [compatibility with map-first preprocessing](https://www.dita-ot.org/dev/extension-points/plugin-extension-points-pre-processing)?

> For maximum compatibility with future versions of DITA-OT, most plug-ins should use the extension points that run before or after pre-processing.

We can't change the core toolkit code to make this work.

**Comment by jason-fox** [comment]
You'll need to reinstall plugins once https://github.com/dita-ot/registry/pull/150 has landed.

**Comment by infotexture** [comment]
Tagged the [5.3.4](https://github.com/infotexture/dita-bootstrap/releases/tag/5.3.4) release and submitted https://github.com/dita-ot/registry/pull/151.
