### ISSUE TITLE
Menubar TOC container structure

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#166]
At some point, the design for the menubar TOC was changed. 

In the previous version, the menubar TOC was part of the main header, and always spanned the full width of the screen.

In the current version, the menubar TOC is in a separate **div** that has **class="container"**. This means that the menubar is never the full width of the screen, since even at smallest screen sizes there's some margin applied:

![menubar](https://github.com/infotexture/dita-bootstrap/assets/108674366/6c7ff653-7ec7-4311-8196-e81f3735d30b)

And on desktop screen sizes the margin is naturally much larger.

Additionally, since the menubar TOC is in a plain **container** and the page content is in a **container-xxl**, the different components do not align at all screen sizes. 

POSSIBLE SOLUTION:

Remove the **container** class from the first wrapping div, and add a new div with **container-xxl** between the navbar and ul components (meaning that the ul is placed inside that new div).

Or, if this is intentional, please disregard. :)

**Comment by infotexture** [comment]
@lakokkonen Good catch. The container was indeed changed to XXL in #130 for #89, and it looks like we forgot to adapt the menubar ToC submenu accordingly.
