### ISSUE TITLE
Footer sticking up in some cases

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#190]
With short topics or empty search results, the footer is halfway up the screen when using mobile screen sizes. 

This also happens in desktop screen sizes if using `nav-toc=none`, since the TOC is "normally" pushing the footer down with the `height=calc(100vh - 6rem)` defined in the `common-extended.css`

A quite common solution is to set the **body** element to have `display: flex, flex-direction: column` and `min-height: 110vh` (for example), and the to set the **footer** to have `margin-top: auto`. These could also be done with Bootstrap classes (besides the min-height in this case) and should work with both mobile and desktop sizes.

**Comment by jason-fox** [comment]
Would amending `common-extended.css` like this be sufficient:

```diff
@media (max-width: 991.98px) {
    .bs-main {
        margin-inline: auto;
+         min-height: calc(80vh - 6rem);
    }
}
```

﻿

**Comment by lakokkonen** [comment]
@jason-fox I think it certainly would. 

Of course, the desired calculated value depends on the height of the header and footer, so if those are something else than the default ones, the user probably needs to set a new value via custom CSS. But I don't think all cases can be covered out of the box.
