### ISSUE TITLE
Create scrollspy TOC also for sections?

### ISSUE THREAD

**Issue by lakokkonen** [infotexture/dita-bootstrap#226]
Not a bug, but a possible feature:

Currently the scrollspy TOC is only created for chunked topics, not sections. 

Would it be a useful feature to also include section titles in the scrollspy TOC, and would it be require a major redesign?

**Comment by infotexture** [comment]
👍 Good suggestion indeed.

There are certainly many publications that use titled sections to structure longer topics, and these cases would benefit from the ability to navigate those sections via the page TOC.

**Comment by jason-fox** [comment]
I have created a [feature branch](https://github.com/jason-fox/dita-bootstrap/tree/feature/section) to implement this, but I'd like to check if the functionality is correct.

At the moment only a `<section>` with an `id` is displayed in the updated scrollspy.


```xml
<section id="non-image-elements">
      <title>With non-image elements</title>
</section>
```

`<section>` elements do not need an `id` - therefore a section without an `id` is ignored.
Also what should be done with a `<section>`  without a `<title>`

```xml
<section>
      <title>This section is ignored</title>
</section>
```

`<section>` elements are used structurally within tabbed dialogs, however a `<section>` within a `<bodydiv>` is also ignored:

```xml
<bodydiv outputclass="nav-tabs">
  <section id="home">
    <title>Home</title>
  </section>
  <section id="profile">
    <title>Profile</title>
  </section>
  <section id="contact">
    <title>Contact</title>
  </section>
</bodydiv>
```


`<section>` elements are used structurally within offcanvas dialogs - I assume these should be ignored.

```
<section outputclass="offcanvas-start" id="offcanvas1">
  <title>Offcanvas</title>
  <p>
    Content for the offcanvas goes here. You can place just about any section elements here.
  </p>
</section>
```

**Comment by lakokkonen** [comment]
@jason-fox At least in my opinion, a `<section>` without a `title` should be ignored. 

I tested the update and it seems to work as intended, even with a mix of chunked topics and sections.
