### ISSUE TITLE
net.infotexture.dita-bootstrap doesn't enable html5-bootstrap

### ISSUE THREAD

**Issue by weiwu-zhang** [infotexture/dita-bootstrap#31]
In my old (dita 3.6) note, I wrote (a year ago) to myself that if  net.infotexture.dita-bootstrap is installed, the html5-bootstrap type will be recognised. the same dita project stopped working with my DITA-OT version 3.7.0

````
$ dita --install net.infotexture.dita-bootstrap
Error: Plug-in net.infotexture.dita-bootstrap already installed: /opt/dita-ot-3.7/plugins/net.infotexture.dita-bootstrap
dita --project config/website.yaml -o out/website
Error: [DOTA001F][FATAL] "html5-bootstrap" is not a recognized transformation type. Supported transformation types are dita, eclipsehelp, html5, htmlhelp, markdown, markdown_gitbook, markdown_github, pdf, pdf2, xhtml.
````
appreciate any hint!

**Comment by infotexture** [comment]
@weiwu-zhang The latest version of the plug-in should work fine with DITA-OT 3.7. 

The error messages above suggest you may have upgraded your old DITA-OT 3.6 installation to 3.7, so the previous plug-in installation was still present when you tried to install it again.

I suggest you remove the plug-in, and then re-install it to ensure it is properly integrated in your updated toolkit environment:

```bash
$ dita uninstall net.infotexture.dita-bootstrap
$ dita install net.infotexture.dita-bootstrap
```

If your `website.yaml` project file specifies the Bootstrap transformation with `transtype: 'html5-bootstrap'`, the output should be generated as expected.

**Comment by weiwu-zhang** [comment]
thank you, the said procedure solved the problem.
