### ISSUE TITLE
Remove `active` class from active page ancestors when using nav pills

### ISSUE THREAD

**Issue by infotexture** [infotexture/dita-bootstrap#32]
- Only one page is really "active"
- Consider highlighting ancestors in alternate color such as `bg-light`

**Comment by jason-fox** [comment]
The existing functionality matches default Bootstrap 5 behaviour - see [Scrollspy](https://getbootstrap.com/docs/5.1/components/scrollspy/#example-with-nested-nav) for an example. I think the default for this - i.e. ancestor highlight - should remain the same, but it would be possible to add an override parameter to highlight ancestors differently, just a matter of not hard-coding `active` in the XSL.

**Comment by infotexture** [comment]
> The existing functionality matches default Bootstrap 5 behaviour 

OK, then I agree this should be the default, regardless of my personal preferences.

The solution in #35 that makes the page ancestor classes configurable seems like the right approach. 👍
