### ISSUE TITLE
Apply map title to the header

### ISSUE THREAD

**Issue by Billy-102** [infotexture/dita-bootstrap#48]
I want to add the map title from DITA source to the header of the html5 output, but I cannot find where the header has been defined. Could you please give some suggestions? (not replace the text "DITA Boostrap" but dynamically apply the map title)

**Comment by jason-fox** [comment]
-  `args.hdr` is a standard DITA-OT [HTML5 build argument](https://www.dita-ot.org/dev/parameters/parameters-html5.html) to add a common header to an HTML document.

The plugin sets a default value [here](https://github.com/infotexture/dita-bootstrap/blob/develop/build_dita2html5-bootstrap.xml#L101-L103). By default this corresponds to the file [`includes/bs-navbar-default.hdr.xml`] (https://github.com/infotexture/dita-bootstrap/blob/develop/includes/bs-navbar-default.hdr.xml#L20) found, which in turn defines a default bootstrap header menu with classes `navbar navbar-expand-lg navbar-dark bg-primary` and  uses the text **DITA Bootstrap** as its `navbar-brand`

**Comment by Billyshane** [comment]
> * `args.hdr` is a standard DITA-OT [HTML5 build argument](https://www.dita-ot.org/dev/parameters/parameters-html5.html) to add a common header to an HTML document.
> 
> The plugin sets a default value [here](https://github.com/infotexture/dita-bootstrap/blob/develop/build_dita2html5-bootstrap.xml#L101-L103). By default this corresponds to the file [includes/bs-navbar-default.hdr.xml](https://github.com/infotexture/dita-bootstrap/blob/develop/includes/bs-navbar-default.hdr.xml#L20), which in turn defines a default bootstrap header menu with classes `navbar navbar-expand-lg navbar-dark bg-primary` and uses the text **DITA Bootstrap** as its `navbar-brand`

I have seen it, but I want to know whether it is possible to replace the text with the map title of the input **.ditamap** ?

**Comment by Billyshane** [comment]
For exmaple, when testA.ditamap with the map title "Test A" is the input , the header can be "Test A"; when testB.ditamap with the map title "Test B" is the input , the header can be "Test B"...

**Comment by jason-fox** [comment]
The banner is generated in [`html5-bootstrap.xsl`](https://github.com/infotexture/dita-bootstrap/blob/develop/xsl/html5-bootstrap.xsl#L95-L112) - it includes a call to the `addHeaderToHtmlBodyElement` template which is found in the standard HTML5 plugin - this is standard functionality not customized by the DITA-Bootstrap plugin

```xml
<xsl:apply-templates select="." mode="addHeaderToHtmlBodyElement"/>
```

That in turn calls a template called `processHDR`:

```xml
  <xsl:template match="*" mode="addHeaderToHtmlBodyElement">
    <xsl:variable name="header-content" as="node()*">
...
      <xsl:call-template name="processHDR"/>
    </xsl:variable>

    <xsl:if test="exists($header-content)">
      <header xsl:use-attribute-sets="banner">
        <xsl:sequence select="$header-content"/>
      </header>
    </xsl:if>
  </xsl:template>
```

You would need to add an override of the following  `mode="processHDR"` template to get this to work 

```xml
 <xsl:template match="/ | @* | node()" mode="processHDR">
    <!-- Add user's running heading XHTML code snippet if requested to -->
    <xsl:if test="string-length($HDRFILE) > 0">
      <xsl:copy-of select="document($HDRFILE, /)"/>      
    </xsl:if>    
  </xsl:template>
```

**Comment by Billyshane** [comment]
> The banner is generated in [`html5-bootstrap.xsl`](https://github.com/infotexture/dita-bootstrap/blob/develop/xsl/html5-bootstrap.xsl#L95-L112) - it includes a call to the `addHeaderToHtmlBodyElement` template which is found in the standard HTML5 plugin - this is standard functionality not customized by the DITA-Bootstrap plugin
> 
> ```
> <xsl:apply-templates select="." mode="addHeaderToHtmlBodyElement"/>
> ```
> 
> That in turn calls a template called `processHDR`:
> 
> ```
>   <xsl:template match="*" mode="addHeaderToHtmlBodyElement">
>     <xsl:variable name="header-content" as="node()*">
> ...
>       <xsl:call-template name="processHDR"/>
>     </xsl:variable>
> 
>     <xsl:if test="exists($header-content)">
>       <header xsl:use-attribute-sets="banner">
>         <xsl:sequence select="$header-content"/>
>       </header>
>     </xsl:if>
>   </xsl:template>
> ```
> 
> You would need to add an override of the following `mode="processHDR"` template to get this to work
> 
> ```
>  <xsl:template match="/ | @* | node()" mode="processHDR">
>     
>     <xsl:if test="string-length($HDRFILE) > 0">
>       <xsl:copy-of select="document($HDRFILE, /)"/>      
>     </xsl:if>    
>   </xsl:template>
> ```

Thank you for your advice, I have tried to modified the `mode="processHDR"` template like this:
```
<xsl:template match="/ | @* | node()" mode="processHDR">
    <xsl:value-of select="*[contains(@class,' map/map ')]/*[contains(@class,' topic/title ')]"/>
</xsl:template>
```
However, the map title cannot be displayed. Is there anything wrong?

**Comment by jason-fox** [comment]
`$HDRFILE` is the contents of the whole [Nav bar Header](https://github.com/infotexture/dita-bootstrap/blob/develop/includes/bs-navbar-default.hdr.xml) - you could paste that in and add `<xsl:value-of select="*[contains(@class,' map/map ')]/*[contains(@class,' topic/title ')]"/>` in place of the hard-coded text.

**Comment by Billyshane** [comment]
Yes, I did paste all the contents in **bs-navbar-default.hdr.xml** in the `mode="processHDR"` template, and I just showed you the modified part. This is the whole codes in this template:
```
  <xsl:template match="/ | @* | node()" mode="processHDR">
    <!-- Add user's running heading XHTML code snippet if requested to -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-bootstrap"
            viewBox="0 0 16 16"
          >
            <path
              d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"
            />
            <path
              d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"
            />
          </svg>
          <xsl:value-of select="*[contains(@class,' map/map ')]/*[contains(@class,' topic/title ')]"/>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"/>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Link One</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link Two</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link Three</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>            
  </xsl:template>
```
The title was still not displayed, so I am doubting whether this line `<xsl:value-of select="*[contains(@class,' map/map ')]/*[contains(@class,' topic/title ')]"/>` can get the title content correctly.

**Comment by jason-fox** [comment]
As you said, the question is whether the map which holds the data is accessible to that function. Do you have a set of ditamaps which replicate the issue? Maybe you need amend: `<xsl:copy-of select="document($HDRFILE, /)"/>` to another variable (and replace the placeholder there). It is difficult to give advice without a concrete example.

**Comment by Billyshane** [comment]
Do you mean to replace `$HDRFILE` to another xsl file?

**Comment by Billyshane** [comment]
Hello,
I have found that such path "*[contains(@class,' map/map ')]/*[contains(@class,' topic/title ')]" cannot match the document tree, because it is processed just within the current topic, not the whole map. However, I do not know how to change the matching scope to the whole map. Could you kindly give me some advice?

**Comment by Billyshane** [comment]
> As you said, the question is whether the map which holds the data is accessible to that function. Do you have a set of ditamaps which replicate the issue? Maybe you need amend: `<xsl:copy-of select="document($HDRFILE, /)"/>` to another variable (and replace the placeholder there). It is difficult to give advice without a concrete example.

I noticed that the output toc.html can be generated by cover.xsl, and in cover.xsl the map title can be generated by the following already defined template:

<xsl:template match="*[contains(@class, ' map/map ')]/*[contains(@class, ' topic/title ')]">
    <h1 class="title topictitle1">
      <xsl:call-template name="gen-user-panel-title-pfx"/>
      <xsl:apply-templates/>
    </h1>
  </xsl:template>
  
  <xsl:template match="*[contains(@class, ' map/map ')]/@title">
    <h1 class="title topictitle1">
      <xsl:call-template name="gen-user-panel-title-pfx"/>
      <xsl:value-of select="."/>
    </h1>
  </xsl:template>

So I wonder if such template can be used in other html pages in the output through directly applying them, so that the map title can be used in topic page.

**Comment by Billyshane** [comment]
> As you said, the question is whether the map which holds the data is accessible to that function. Do you have a set of ditamaps which replicate the issue? Maybe you need amend: `<xsl:copy-of select="document($HDRFILE, /)"/>` to another variable (and replace the placeholder there). It is difficult to give advice without a concrete example.


This issue is still confusing me now.

This is my test map:

[test.zip](https://github.com/infotexture/dita-bootstrap/files/9417707/test.zip)

**Comment by jason-fox** [comment]
As stated in the docs, you could generate separate docs  using the `--args.hdr` parameter:

```console
dita --input=path/to/your.ditamap \
     --format=html5-bootstrap \
     --args.hdr=path/to/your-header.xml
``` 

If you are looking for a more dynamic header bar, then that would probably be best moved to a separate plugin.
