### ISSUE TITLE
Issues with table borders 

### ISSUE THREAD

**Issue by Billy-102** [infotexture/dita-bootstrap#49]
There is no border on the left side in all tables with different frames, and the colsep borders are in different size within one table: 

![image](https://user-images.githubusercontent.com/94583069/186416712-9bc8425c-27ee-4ac0-ae70-accfe47eaf6b.png)

Is it attentionally designed like this?

**Comment by jason-fox** [comment]
Which version of the plugin? Can you provide some DITA for your table?  The 5.2 [PR](https://github.com/infotexture/dita-bootstrap/pull/46) renders tables without `colsep` like this:


<img width="446" alt="Screenshot 2022-08-24 at 16 33 49" src="https://user-images.githubusercontent.com/3439249/186446802-025b78c5-145b-4681-98be-23e5c664c613.png">


<img width="439" alt="Screenshot 2022-08-24 at 16 33 42" src="https://user-images.githubusercontent.com/3439249/186446812-2235f896-a720-443b-bf55-0ef52797d0d2.png">


<img width="449" alt="Screenshot 2022-08-24 at 16 33 35" src="https://user-images.githubusercontent.com/3439249/186446817-b184ed0c-5914-42f7-966a-0e8499a5eac2.png">


<img width="477" alt="Screenshot 2022-08-24 at 16 33 25" src="https://user-images.githubusercontent.com/3439249/186446821-560f8775-8835-40b4-b330-da07c4262329.png">

**Comment by Billyshane** [comment]
The version of the plugin is `5.3.1`
This is my test source:
[test.zip](https://github.com/infotexture/dita-bootstrap/files/9417552/test.zip)

**Comment by jason-fox** [comment]
The artifact you are getting is due to the standard HTML5 plugin CSS for `rowsep` and `colsep` combining with the Bootstrap 5.1 CSS.Bootstrap introduced `table-bordered` and `table-borderless`  CSS in Bootstrap 5.2 - I have amended the PR to take `rowsep` and `colsep` into consideration.

**Comment by Billyshane** [comment]
Ok, thank you.
How should I get access to the amended version?

**Comment by Billyshane** [comment]
I have tested the modification, and found that the `@frame` property has been asigned to the parent element of the table `<div>`, so the the output appears like:

![image](https://user-images.githubusercontent.com/94583069/186643028-ec373630-fe81-4975-80ed-7439f415c961.png)

It is a little bit different with the preview of the dita source.
![image](https://user-images.githubusercontent.com/94583069/186643861-63a0ada1-87ad-442b-92cf-d3975030ab63.png)

Shall I put the the support for `@frame `to the element `<table></table>`?

**Comment by jason-fox** [comment]
The change follows the definition in the DITA specification for [table](https://docs.oasis-open.org/dita/v1.1/OS/langspec/langref/table.html)

> Specifies which portion of a border should surround the element. Allowable values are:
>
> - `top`  - Draw a line before the element
> - `bottom` - Draw a line after the element
> - `topbot` - Draw a line both before and after the element
> - `all` - Draw a box around the element
> - `sides` - Draw a line at each side of the element
> - `none` - Don't draw any lines around this element

The element in this case is `<table>` and so the frame occurs around the table.

**Comment by Billyshane** [comment]
All right. My understanding is that the @frame is defined for the outer border of a table,  while the @rowsep and @colsep are defined for the inner border of a table:
![image](https://user-images.githubusercontent.com/94583069/186651240-9f661f6a-0f6a-49e9-aec6-449f03af1bf9.png)

Through different values of `@frame` or `@rowsep` or `@colsep` we control the borders of a table.

**Comment by jason-fox** [comment]
`@frame` is a common attribute across many elements, not just`<table>`. Within this plugin, `@frame="all"` draws a box around the element in a consistent fashion for `<table>` , `<codeblock>`, `<figure>`  and `<lines>`  such as [here](https://infotexture.github.io/dita-bootstrap/utilities.html) and [here](https://infotexture.github.io/dita-bootstrap/figures.html) - `<table>` should be no different to the others.

Bootstrap applies its default styling to tables so the look-and-feel is consistent, the default is similar to the DITA-OT HTML5 plugin's interpretation of `<table frame="topbot">` but there isn't a one-to-one correlation between the DITA-OT HTML5 plugin's interpretation of how to render tables and Bootstrap's understanding of this. 

As the spec states:

> Some DITA processors or output formats may not be able to support all values.

**Comment by jason-fox** [comment]
If you amended or removed the Bootstrap padding `pt-3 ps-3 pe-3` found [here](https://github.com/infotexture/dita-bootstrap/blob/d1e81c3ff93058ac01bf027f16737fb64a1a077c/Customization/xsl/tables.xsl#L49-L68), you may get closer to  what you want, but then this would be differ from  `<codeblock>`,`<figure>` and `<lines>`

**Comment by rowsep** [comment]
Tie me up with a bootstrap and call me daddy
