### ISSUE TITLE
Collapsible nav-toc does not work when the map using "chunk=to-content" attribute

### ISSUE THREAD

**Issue by Billy-102** [infotexture/dita-bootstrap#52]
Hi, @infotexture 

I applied `@chunk="to-content"` to the map in order to generate a single html. However, I found that the collapsible nav-toc did not work. In specific, the nav-toc item of current topic cannot be highlighted.

I have figured it out that this is because the class "active" cannot be added to the current nav item in this kind of transformation, but I have no idea on how to modify it to make the collapsible nav-toc compatible with single html output.

Could you please give me some suggestions?

**Comment by jason-fox** [comment]
Note that there is still a  timing problem with using a side-toc with `@chunk="to-content" `, in that the nav bar is rendered before the content, so that if the main content is still in the process of rendering, the anchors for the nav won't be available and navigation won't work until all of the document is rendered.

**Comment by Billy-102** [comment]
> all of the document is rendered.

I did find that question. With `@chunk="to-content"`, the side-toc item cannot be expanded and highlighted to be consistent with the current topic. I have noticed that without `@chunk="to-content"`, the side-toc item is linked with the corresponding output html of each topic (**[topic_file_name].html**), while with `@chunk="to-content"`, the side-toc item is linked with the single html of the whole map (**[map_file_name].html**) + `#topic_id`

**Comment by jason-fox** [comment]
If you are still getting errors of the form:

```
 [xslt] An empty sequence is not allowed as the first argument of dita-ot:generate-html-id()
     [xslt] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the first argument of dita-ot:generate-html-id()
```

Then the issue will still occur. However just rendering ordinary `<topic>` element is fine. I was using the sample doc and I noticed an issue with `offcanvas.dita` so I just commented it out. The suggested fix was for the nav only.

**Comment by Billy-102** [comment]
> If you are still getting errors of the form:
> 
> ```
>  [xslt] An empty sequence is not allowed as the first argument of dita-ot:generate-html-id()
>      [xslt] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the first argument of dita-ot:generate-html-id()
> ```
> 
> Then the issue will still occur. However just rendering ordinary `<topic>` element is fine. I was using the sample doc and I noticed an issue with `offcanvas.dita` so I just commented it out. The suggested fix was for the nav only.

I haven't met this issue, and I am just confused that the selected nav-toc cannot be set "active" anymore, so I come here to ask you if I can modify some lines to make it work normally as it is transformed without `@chunk="to-content"`.

**Comment by jason-fox** [comment]
You can see  a working chunked example here: https://jason-fox.github.io/dita-bootstrap/Chunk2050729693.html I created it from the `feature/5.2` branch.  The collapsible nav now works as do the collapse and offcanvas components.

This was created by altering the ditamap

```diff
- <chapter>
+ <chapter chunk="to-content">
...
- <chapter>
+ <chapter chunk="to-content">
... etc.
```

https://jason-fox.github.io/dita-bootstrap/Chunk1343199979.html demonstrates the timing bug. Nav works eventually, but the DOM needs to complete loading.

**Comment by Billy-102** [comment]
Thank you, I have wrote a javasript for the sibebar-nav to make nav item can be positioned and highlighted automatically when the topic is on the current screen. And I am now considering embeding it to the plugin; how can I chieve that please?









在 2022-09-06 14:13:28，"Jason Fox" ***@***.***> 写道：

You can see a working chunked example here: https://jason-fox.github.io/dita-bootstrap/Chunk2050729693.html I created it from the feature/5.2 branch. The collapsible nav now works as do the collapse and offcanvas components.

This was created by altering the ditamap

- <chapter>+ <chapter chunk="to-content">
...
- <chapter>+ <chapter chunk="to-content">
... etc.

https://jason-fox.github.io/dita-bootstrap/Chunk1343199979.html demonstrates the timing bug. Nav works eventually, but the DOM needs to complete loading.
