### ISSUE TITLE
Add javasript into the html5

### ISSUE THREAD

**Issue by Billy-102** [infotexture/dita-bootstrap#53]
Hi, @jason-fox 
I have a javascript for the output html5. Can I write it directly in the html? If not, how can I embed it in the output html5 correctly?

**Comment by infotexture** [comment]
This question is not specific to the DITA Bootstrap plug-in.

For details on embedding JavaScript in HTML output from DITA-OT, see
See https://www.dita-ot.org/dev/topics/html-customization-plugin-javascript.html
